# Setup
title:            Max Nicosia PhD
tagline:          'My Personal Website'
description:      'Researcher, Software Developer and Consultant.'
url:              https://lumyx2.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Max Nicosia PhD'
  url:            https://lumyx2.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
