# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Max Nicosia PhD
tagline:          'My Personal Website'
description:      'Researcher, Software Developer, and Consultant.'
url:              http://lumyx2.github.io
baseurl:          /

author:
  name:           'Max Nicosia PhD'
  url:            https://lumyx2.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://lumyx2.github.io
